services:
  app:
    image: docker.io/dreace233/yattr:latest
    pull_policy: always
    ports:
      - "8001:8000"
    environment:
      - RSS_DB_URL=sqlite:///./data/rss.sqlite
      - RSS_SECRET_KEY=${RSS_SECRET_KEY}
      - RSS_ADMIN_EMAIL=${RSS_ADMIN_EMAIL}
      - RSS_ADMIN_PASSWORD=${RSS_ADMIN_PASSWORD}
      - RSS_PLUGINS=fever
    volumes:
      - ./data:/app/data
