services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.single
      target: runtime
    ports:
      - "8001:8000"
    environment:
      - RSS_DB_URL=sqlite:///./data/rss.sqlite
      - RSS_SECRET_KEY=change_me
      - RSS_ADMIN_EMAIL=${RSS_ADMIN_EMAIL}
      - RSS_ADMIN_PASSWORD=${RSS_ADMIN_PASSWORD}
      - RSS_PLUGINS=fever
    volumes:
      - ./data:/app/data
